// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 27-02-2025, 5:51:34 p. m.
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/projects/sb1-jlx3mzoq/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-jlx3mzoq/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-jlx3mzoq/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-jlx3mzoq/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-jlx3mzoq/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-jlx3mzoq/plugins/**/*.{js,ts,mjs}","/home/projects/sb1-jlx3mzoq/composables/**/*.{js,ts,mjs}","/home/projects/sb1-jlx3mzoq/utils/**/*.{js,ts,mjs}","/home/projects/sb1-jlx3mzoq/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-jlx3mzoq/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-jlx3mzoq/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;