// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 27-02-2025, 5:58:08 p. m.
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/iCONIC0/corporacion-ahra/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/iCONIC0/corporacion-ahra/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/iCONIC0/corporacion-ahra/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/iCONIC0/corporacion-ahra/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/iCONIC0/corporacion-ahra/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/iCONIC0/corporacion-ahra/plugins/**/*.{js,ts,mjs}","/home/iCONIC0/corporacion-ahra/composables/**/*.{js,ts,mjs}","/home/iCONIC0/corporacion-ahra/utils/**/*.{js,ts,mjs}","/home/iCONIC0/corporacion-ahra/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/iCONIC0/corporacion-ahra/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/iCONIC0/corporacion-ahra/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;